version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: cron
      cronjob: "0 10 5 * *"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "0 10 5 * *"
